### ISSUE TITLE
SugarMelt not working in Firefox 124.0

### ISSUE THREAD

**Issue by kru666** [lure0xaos/SugarMelt#1]
Extension was installed from Mozilla addons store and looks like there is not enough permissions. No menu when F12 pressed. Icon of SugarMelt says: Can't read and change data on this site. 
Tested on Degrees of Lewdity

**Comment by Tuulipommi** [comment]
Still an active issue.

**Comment by hikaru-shindo** [comment]
Just fixed it in #3. Hope @lure0xaos will merge or use it.

**Comment by kru666** [comment]
I think that issue was fixed. At least now it is fully accessible in ff. Close
